#!/usr/bin/env bash
# this program prints the number from 1 to 100, writing Fizz if the number is multiple of 3,
# Buzz if the number is multiple of 5, and FizzBuzz if the number is multiple of 3 and 5.
for ((x=1; x<=100; x++))
do
	if ((x%3==0&&x%5==0))
	then
		echo FizzBuzz
	elif ((x%3==0))
	then
		echo Fizz
	elif ((x%5==0))
	then
		echo Buzz
	else
		echo $x
	fi
done
