#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, and "Hi" after the 9th iteration.
counter=0
while [ $counter -lt 10 ]
do
	echo Holberton School
	if [ $counter -eq 8 ]
	then
		echo Hi
	fi
	((counter++))
done
